name: Publish Doxygen Documentation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Doxygen
        run: sudo apt-get install -y doxygen

      - name: Generate Doxygen Documentation
        run: doxygen Doxyfile

      - name: Deploy to GitHub Pages
        uses: DenverCoder1/doxygen-github-pages-action@v1.3.0
        with:
          branch: gh-pages
          folder: ./docs/html 
